[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("样式", "IDE0044:添加只读修饰符", Justification = "<挂起>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("样式", "IDE0017:简化对象初始化", Justification = "<挂起>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("样式", "IDE0028:简化集合初始化", Justification = "<挂起>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("样式", "IDE1006:命名样式", Justification = "<挂起>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("样式", "IDE0019:使用模式匹配", Justification = "<挂起>")]
